language: objective-c
rvm: 2.2.2
cache: cocoapods
before_install:
  - gem install cocoapods -v '>= 1.0.0.beta' --no-rdoc --no-ri --no-document
  - pod setup
matrix:
 include:
  - osx_image: xcode6.4
    env: SDK=iphonesimulator8.4
  - osx_image: xcode7.3
    env: SDK=iphonesimulator9.3
  - osx_image: xcode8.2
    env: SDK=iphonesimulator10.1

script:
  - xctool -workspace Habitica.xcworkspace -scheme Habitica -sdk $SDK ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace Habitica.xcworkspace -scheme HabiticaTests -sdk $SDK ONLY_ACTIVE_ARCH=NO
  - swiftlint
