language: objective-c
cache: cocoapods
osx_image: xcode8.2
rvm:
  - 2.2
install:
  - gem install cocoapods
  - gem install xcpretty -N
  - gem install xcpretty-travis-formatter
  - gem install cocoapods-keys -v 1.7.0
  - brew update
  - brew install swiftlint || true
  - brew outdated swiftlint || brew upgrade swiftlint
  - bundle exec pod repo update
  - bundle exec pod install
env:
  global:
    - GoogleClient=123
    - GoogleRedirectUrl=123
    - AmplitudeApiKey=123
    - SeedsDevApiKey=123
    - SeedsReleaseApiKey=123
    - SeedsDevGemsInterstitial=123
    - SeedsReleaseGemsInterstitial=123
    - SeedsReleaseShareInterstitial=123
    - SeedsDevShareInterstitial=123
    - ItunesSharedSecret=123
    - FB_REFERENCE_IMAGE_DIR="./ReferenceImages_32"
  matrix:
#    - DESTINATION="platform=iOS Simulator,name=iPhone 6,OS=8.4"
#    - DESTINATION="platform=iOS Simulator,name=iPhone 6,OS=9.3"
    - DESTINATION="platform=iOS Simulator,name=iPhone 6,OS=10.1"
script:
  - set -o pipefail
  - xcodebuild -workspace Habitica.xcworkspace -scheme HabiticaTests -destination "$DESTINATION" -sdk iphonesimulator10.2 test ONLY_ACTIVE_ARCH=NO > /dev/null
#  - xcodebuild -workspace Habitica.xcworkspace -scheme HabiticaTests -destination "$DESTINATION" -sdk iphonesimulator10.2 test ONLY_ACTIVE_ARCH=NO | xcpretty  -f `xcpretty-travis-formatter`
  - swiftlint
