language: objective-c
cache: cocoapods
install:
  - rvm install ruby-2.2.2
  - gem install cocoapods
  - gem install xcpretty -N
  - gem install cocoapods-keys -v 1.7.0
  - brew update
  - brew install swiftlint || true
  - brew upgrade swiftlint || true
  - pod repo update
  - pod install
env:
  global:
    - GoogleClient=123
    - GoogleRedirectUrl=123
    - AmplitudeApiKey=123
    - SeedsDevApiKey=123
    - SeedsReleaseApiKey=123
    - SeedsDevGemsInterstitial=123
    - SeedsReleaseGemsInterstitial=123
    - SeedsReleaseShareInterstitial=123
    - SeedsDevShareInterstitial=123
    - ItunesSharedSecret=123
matrix:
 include:
  - osx_image: xcode6.4
    env: SDK=iphonesimulator8.4
  - osx_image: xcode7.3
    env: SDK=iphonesimulator9.3
  - osx_image: xcode8.2
    env: SDK=iphonesimulator10.2
script:
  - xctool -workspace Habitica.xcworkspace -scheme Habitica -sdk $SDK ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace Habitica.xcworkspace -scheme HabiticaTests -sdk $SDK ONLY_ACTIVE_ARCH=NO
  - swiftlint
