language: objective-c
cache: cocoapods
osx_version: xcode8.2
install:
  - rvm install ruby-2.2.2
  - gem install cocoapods
  - gem install xcpretty -N
  - gem install xcpretty-travis-formatter
  - gem install cocoapods-keys -v 1.7.0
  - brew update
  - brew install swiftlint || true
  - brew upgrade swiftlint || true
  - pod repo update
  - pod install
env:
  global:
    - GoogleClient=123
    - GoogleRedirectUrl=123
    - AmplitudeApiKey=123
    - SeedsDevApiKey=123
    - SeedsReleaseApiKey=123
    - SeedsDevGemsInterstitial=123
    - SeedsReleaseGemsInterstitial=123
    - SeedsReleaseShareInterstitial=123
    - SeedsDevShareInterstitial=123
    - ItunesSharedSecret=123
  matrix:
    - DESTINATION="platform=iOS Simulator,name=iPhone 6,OS=8.4"
    - DESTINATION="platform=iOS Simulator,name=iPhone 6,OS=9.3"
    - DESTINATION="platform=iOS Simulator,name=iPhone 6,OS=10.2"
script:
  - set -o pipefail
  - xcodebuild -workspace Habitica.xcworkspace -scheme HabiticaTests -destination "$DESTINATION" test ONLY_ACTIVE_ARCH=NO | xcpretty -f `xcpretty-travis-formatter`
  - swiftlint
