language: objective-c
cache: cocoapods
osx_image: xcode8.2
install:
  - rvm install ruby-2.2.2
  - gem install cocoapods
  - gem install xcpretty -N
  - gem install cocoapods-keys -v 1.7.0
  - brew update
  - brew install swiftlint || true
  - pod install
env:
  global:
    - GoogleClient=123
    - GoogleRedirectUrl=123
    - AmplitudeApiKey=123
    - SeedsDevApiKey=123
    - SeedsReleaseApiKey=123
    - SeedsDevGemsInterstitial=123
    - SeedsReleaseGemsInterstitial=123
    - SeedsReleaseShareInterstitial=123
    - SeedsDevShareInterstitial=123
    - ItunesSharedSecret=123
  matrix:
    - SDK=iphonesimulator8.4
    - SDK=iphonesimulator9.3
    - SDK=iphonesimulator10.1
script:
  - xctool -workspace Habitica.xcworkspace -scheme Habitica -sdk $SDK ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace Habitica.xcworkspace -scheme HabiticaTests -sdk $SDK ONLY_ACTIVE_ARCH=NO
  - swiftlint
